title: "Amyas Merivale"
description: "Personal web site of Amyas Merivale."
markdown: kramdown
kramdown:
  parse_block_html: true
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
orcid: 0000-0002-6301-6419
scopus: 44461866400
github: merivale
