title: "Amyas Merivale"
description: "Personal web site of Amyas Merivale."
markdown: kramdown
kramdown:
  parse_block_html: true
sass:
  style: compressed
defaults:
  - scope:
      path: ""
    values:
      layout: "site"
orcid: https://orcid.org/0000-0002-6301-6419
scopus: https://www.scopus.com/authid/detail.uri?authorId=44461866400
routledge: http://www.routledge.com/authors/i18300-amyas-merivale
github: https://github.com/merivale
linkedin: https://www.linkedin.com/in/amyas-merivale-845859158
